name: Deploy Laravel Application to Production Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3

    - name: Install Composer Dependencies
      run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install NPM Dependencies
      run: npm install

    - name: Build NPM Assets
      run: npm run build

    - name: Synchronize Files To Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 152.42.242.130
        username: root
        password: 1332@!Minhaz**M
        script: |
          rsync -avz --exclude '.git' . root@152.42.242.130:/var/www/html/prodapp/
          cd /var/www/html/prodapp
          php artisan migrate --force
          php artisan optimize
